(function(){'use strict';
const D=window.PERMEATE_DATA;if(!D)return;const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function text(v){if(Array.isArray(v))return v.join('; ');if(v&&typeof v==='object')return Object.entries(v).map(([k,x])=>k.replaceAll('_',' ')+': '+text(x)).join('; ');return String(v??'Not specified');}
const TAG_LABELS={indicative_planning:'Indicative planning reference',modeled:'Modeled example',scope_outline:'Scope outline'};
function tagLabel(v){return TAG_LABELS[v]||text(v).replaceAll('_',' ');}
function plain(v){return text(v).replace(/\bZCTA\b/g,'ZIP area');}
function money(v){return v==null?'':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);}
function range(s){return s.low==null?'Scope-based quote needed':money(s.low)+(s.high!=null?'–'+money(s.high)+(s.high_is_open?'+':''):' and up');}
function li(a){return '<ul class="list">'+(a||[]).map(x=>'<li>'+esc(text(x))+'</li>').join('')+'</ul>';}
function resultHtml(r){
 const methodHref=document.getElementById('methodology')?'#methodology':'methodology.html';
 const area=r.requested_area.counties.join(', ')+(r.requested_area.counties.length>1?' counties':' County');
 const extra='';
 return '<div class="card"><span class="tag">'+esc(tagLabel(r.range_type))+'</span><h2 style="margin-top:15px">'+esc(r.service_variant)+'</h2><div class="number">'+range(r)+'</div><p class="basis">'+esc(text(r.price_basis))+'</p><div class="notice"><strong>ZIP '+esc(r.requested_area.zip)+' · '+esc(area)+'</strong><p style="margin-top:8px">Regional planning guidance for Bay, Walton and Okaloosa counties. This is not a ZIP-specific observed price; confirm the written scope and any minimum fee.</p>'+extra+'<a href="'+methodHref+'">How to use this reference</a></div><p class="meta">Research cutoff '+esc(new Date(r.research_cutoff+'T00:00:00Z').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}))+'</p>'+(r.assumptions&&r.assumptions.length?'<h3>Scenario assumptions</h3>'+li(r.assumptions):'')+'<p class="small">Scope tier, credential, site visit, sampling and minimum fee are not fixed by this reference. Unknown details are not exclusions.</p><h3>Scope changes the budget</h3>'+li(r.scope_drivers)+'<h3>Fee reference includes</h3>'+li(r.inclusions)+'<h3>Keep separate</h3>'+li(r.exclusions)+'<h3>Questions for comparable proposals</h3>'+li(r.questions)+'<p class="small"><strong>Area context:</strong> '+esc(r.geographic_context.registered_projects??'Not available')+' registered project records and '+esc(r.geographic_context.registered_units??'Not available')+' registered units allocated to this ZIP. Source ZIP allocation is incomplete; a zero does not establish absence.</p><p class="small subtle">Area references describe geographic areas, not individual properties or engagements.</p><div class="link-row no-print"><button type="button" id="print-brief">Print board brief</button><button type="button" class="secondary" id="download-answer">Download this answer (JSON)</button></div><p class="meta">Edition '+esc(r.release_id)+'</p><p class="small">Reference: <a href="'+esc(r.canonical_url||'https://permeatelab.com/research/northwest-florida-engineering-costs/')+'">'+esc(r.canonical_url||'https://permeatelab.com/research/northwest-florida-engineering-costs/')+'</a></p></div>';
}
function blobDownload(name,content,type){const u=URL.createObjectURL(new Blob([content],{type:type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
window.PermeateReview={data:D,lookup:(zip,id,scope)=>PermeateLookup.lookup(D.services,D.geography,zip,id,scope),lookupLocality:(query,id,scope,zip)=>PermeateLookup.lookupLocality(D.services,D.geography,D.localities,query,id,scope,zip)};
const serviceGuideLinks=()=>'<p>Regional service guides: '+D.services.services.map(x=>'<a href="services/'+esc(x.id)+'.html">'+esc(x.name)+'</a>').join(' · ')+'.</p><p><a href="index.html">Back to the cost reference</a> · <a href="methodology.html">Method and data</a></p>';
const zipChoices=(r,intro)=>'<div class="notice"><p>'+esc(intro)+'</p>'+(r.geography_note?'<p class="small">'+esc(plain(r.geography_note))+'</p>':'')+'<div class="link-row no-print">'+r.choices.map(z=>'<button type="button" class="secondary" data-zip-choice="'+esc(z)+'">ZIP '+esc(z)+'</button>').join('')+'</div></div>';
function messageHtml(r){
 if(r.status==='selection_required'&&r.selection_type==='zip')return zipChoices(r,(r.locality_label||'This community')+' spans more than one ZIP area. Choose the one that matches the site.');
 if(r.status==='invalid_locality_zip')return zipChoices(r,'The ZIP you entered is not an associated ZIP area for the selected community. Choose one of its ZIP areas, or clear the community to look up the ZIP on its own.');
 if(r.status==='unsupported_area')return '<div class="notice error"><p>'+esc(r.message)+'</p>'+serviceGuideLinks()+'</div>';
 return '<div class="notice error"><p>'+esc(r.message)+'</p></div>';
}
const community=$('#community');if(community)community.addEventListener('change',()=>{const area=(D.localities.localities||[]).find(x=>x.id===community.value);const note=$('#community-note');if(!area){note.textContent='';return;}note.textContent=plain(area.geography_note)+' Associated ZIP areas: '+area.zctas.join(', ')+'. Regional planning context only.';if(area.zctas.length===1)$('#zip').value=area.zctas[0];else{$('#zip').value='';const node=$('#lookup-result');if(node)node.innerHTML=zipChoices({choices:area.zctas},area.label+' spans more than one ZIP area. Choose the one that matches the site, then look up the area.');}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-zip-choice]');if(!b)return;$('#zip').value=b.dataset.zipChoice;const f=$('#lookup-form');if(f){if(f.requestSubmit)f.requestSubmit();else f.dispatchEvent(new Event('submit',{cancelable:true}));}});
const form=$('#lookup-form');if(form){const updateScopes=()=>{const s=D.services.services.find(s=>s.id===$('#service').value);$('#scope').innerHTML='<option value="base">Base planning reference</option>'+(s.scenarios||[]).map(x=>'<option value="'+esc(x.id)+'">'+esc(x.label)+'</option>').join('');};$('#service').addEventListener('change',updateScopes);updateScopes();form.addEventListener('submit',e=>{e.preventDefault();const picked=community&&community.value;const r=picked?PermeateLookup.lookupLocality(D.services,D.geography,D.localities,picked,$('#service').value,$('#scope').value,$('#zip').value.trim()||undefined):PermeateLookup.lookup(D.services,D.geography,$('#zip').value,$('#service').value,$('#scope').value);const node=$('#lookup-result');node.innerHTML=r.status==='available'?resultHtml(r):messageHtml(r);node.tabIndex=-1;node.focus();if(r.status==='available'){$('#download-answer').onclick=()=>blobDownload('permeate-area-answer.json',JSON.stringify(r,null,2),'application/json');$('#print-brief').onclick=()=>{const p=$('#print-area');if(p){p.innerHTML='<h1>Engineering scope and budget brief</h1>'+resultHtml(r).replaceAll('id="print-brief"','').replaceAll('id="download-answer"','');document.body.classList.add('printing-brief');window.print();document.body.classList.remove('printing-brief');p.innerHTML='';}else window.print();};}});}
const compare=$('#compare-form');if(compare){compare.addEventListener('submit',e=>{e.preventDefault();const rows=Array.from(document.querySelectorAll('[data-scope-row]'));const norm=v=>v.trim().toLocaleLowerCase('en-US').replace(/\s+/g,' ').replace(/[.;:,]+$/,'');const differences=rows.map(row=>{const name=row.dataset.scopeRow,a=row.querySelector('[data-quote="a"]').value.trim(),b=row.querySelector('[data-quote="b"]').value.trim();return {scope:name,quote_a:a||'Not specified',quote_b:b||'Not specified',blank:!a&&!b,partial:(!a)!==(!b),same:!!a&&!!b&&norm(a)===norm(b)};});const blank=differences.filter(r=>r.blank);const partial=differences.filter(r=>r.partial);const changed=differences.filter(r=>!r.blank&&!r.partial&&!r.same);$('#compare-result').innerHTML='<div class="card"><h2>Your scope comparison</h2><p>'+changed.length+' of '+rows.length+' scope items differ between the proposals. '+partial.length+' specified in only one proposal. '+blank.length+' left blank in both.</p>'+(changed.length?'<h3>Different</h3>'+li(changed.map(r=>r.scope+': A = '+r.quote_a+'; B = '+r.quote_b)):'')+(partial.length?'<h3>Specified in only one proposal</h3>'+li(partial.map(r=>r.scope+': A = '+r.quote_a+'; B = '+r.quote_b)):'')+ '<p class="small subtle">This comparison identifies scope differences. It does not estimate the cost of omitted work or judge which proposal offers better value. Entries remain in your browser and are not submitted.</p></div>';$('#compare-result').tabIndex=-1;$('#compare-result').focus();});}
document.querySelectorAll('[data-export]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const type=a.dataset.export;if(type==='services')blobDownload('permeate-services.json',JSON.stringify(D.services,null,2),'application/json');if(type==='geography')blobDownload('permeate-geography.json',JSON.stringify(D.geography,null,2),'application/json');if(type==='localities')blobDownload('permeate-localities.json',JSON.stringify(D.localities,null,2),'application/json');if(type==='taxonomy')blobDownload('permeate-service-taxonomy.json',JSON.stringify(D.taxonomy,null,2),'application/json');if(type==='csv')blobDownload('permeate-pricing.csv',D.csv,'text/csv;charset=utf-8');}));
const generalPrint=$('#print-comparison');if(generalPrint)generalPrint.onclick=()=>{const p=$('#print-area');const clone=$('#comparison').cloneNode(true);clone.querySelectorAll('input').forEach((el,i)=>{const out=document.createElement('span');out.textContent=$('#comparison').querySelectorAll('input')[i].value.trim()||'Not specified';el.replaceWith(out);});clone.querySelectorAll('button').forEach(el=>el.remove());p.innerHTML=clone.outerHTML;document.body.classList.add('printing-brief');window.print();document.body.classList.remove('printing-brief');p.innerHTML='';};
})();
